// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzWCIIYZMQKDMIHC8b6d8mC5dof9216E',
    appId: '1:613447001121:web:d61ff160941eeecea96f60',
    messagingSenderId: '613447001121',
    projectId: 'kanban-proyect',
    authDomain: 'kanban-proyect.firebaseapp.com',
    databaseURL: 'https://kanban-proyect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanban-proyect.firebasestorage.app',
    measurementId: 'G-VTWPEWL53V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRAIF35L1gJOTIRkTnvUX4-7Z0Frn5bPk',
    appId: '1:613447001121:android:cc936a778b5ea02ba96f60',
    messagingSenderId: '613447001121',
    projectId: 'kanban-proyect',
    databaseURL: 'https://kanban-proyect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanban-proyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKV3OROljhuNsgz5kJptxpbJXUw_gyCM4',
    appId: '1:613447001121:ios:0a177e8c5affbe39a96f60',
    messagingSenderId: '613447001121',
    projectId: 'kanban-proyect',
    databaseURL: 'https://kanban-proyect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanban-proyect.firebasestorage.app',
    iosBundleId: 'com.example.kanbanClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKV3OROljhuNsgz5kJptxpbJXUw_gyCM4',
    appId: '1:613447001121:ios:0a177e8c5affbe39a96f60',
    messagingSenderId: '613447001121',
    projectId: 'kanban-proyect',
    databaseURL: 'https://kanban-proyect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanban-proyect.firebasestorage.app',
    iosBundleId: 'com.example.kanbanClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhzWCIIYZMQKDMIHC8b6d8mC5dof9216E',
    appId: '1:613447001121:web:f128c937aa2ee9bea96f60',
    messagingSenderId: '613447001121',
    projectId: 'kanban-proyect',
    authDomain: 'kanban-proyect.firebaseapp.com',
    databaseURL: 'https://kanban-proyect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanban-proyect.firebasestorage.app',
    measurementId: 'G-HT0C54X9L7',
  );
}
